### ISSUE TITLE
BlackList申请：是水还是果（1796197141）

### ISSUE THREAD

**Issue by CoolPlayLin** [Codemao-Python-Rules-Commissions/Commands#8]
## 缘由
1. 该群成员多次异常退出 Python 群又重新加入Python群
2. 10月5日在群内利用机器人恶意刷屏，且企图通过退出群聊逃避处罚

## 截图
- 退出群聊
![image](https://github.com/Codemao-Python-Rules-Commissions/Commands/assets/96709586/7db783ec-4570-495f-aaae-f0029c4eac7f)
- 利用机器人恶意刷屏且带有辱骂字眼
![image](https://github.com/Codemao-Python-Rules-Commissions/Commands/assets/96709586/cfa475d6-6e3f-45ac-a638-e52213bad0e2)
![image](https://github.com/Codemao-Python-Rules-Commissions/Commands/assets/96709586/d8bd7b34-f95c-4521-9c3f-59ddce5e06ce)
![image](https://github.com/Codemao-Python-Rules-Commissions/Commands/assets/96709586/900a384d-a136-49e5-a7e9-a10fecbcb0d2)

**Comment by liulyxandy-codemao** [comment]
好好好
